### ISSUE TITLE
[request] Add pouch in 容器

### ISSUE THREAD

**Issue by gaocegege** [gocn/knowledge#1]
> Pouch is an open-source project created by Alibaba Group to promote the container technology movement.

Pouch has some [addtional features](https://github.com/alibaba/pouch/blob/9b769f7ea50890b565c2876004ac12982d0f0f20/FAQ.md#what-is-difference-between-pouch-and-docker) compared to docker. Then I think we could add pouch as an option.

**Comment by astaxie** [comment]
added
